### ISSUE TITLE
Exception when trying to connect to server (both singleplayer and multiplayer)

### ISSUE THREAD

**Issue by Steveplays28** [SilkMC/silk#51]
[Exception log](https://mclo.gs/d0SVQCr)
[Full log](https://mclo.gs/39LyVOu)

Works if Silk (and dependant mods) are removed from the server (or removed from the client if singleplayer).

**Comment by jakobkmar** [comment]
Hi, thanks a lot for the report!

I think this has already been fixed in the latest three commits, but sadly I cannot publish the release because I forgot to bring my gpg keys with me on vacation.

I am sorry for the inconvenience - I will publish the fixed release as soon as I am back home.

For anyone who needs the fix more quickly, compile the latest git state of this repo.

Related: #50 and some discussions on the Discord

**Comment by Steveplays28** [comment]
Thank you for fixing the issue, I'll try compiling the latest commits. Appreciate the quick response!

**Comment by jakobkmar** [comment]
Should now be fixed with [1.10.1](https://github.com/SilkMC/silk/releases/tag/1.10.1).
